version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgresDB
      - DB_SOURCE=postgresql://postgresUser:postgres@postgres:5432/postgresDB?sslmode=disable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgresDB -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_SOURCE=postgresql://postgresUser:postgres@postgres:5432/postgresDB?sslmode=disable
      - GIN_MODE=release
    depends_on:
      postgres:
        condition: service_healthy
